version: "2.1"
services:
  scm-frontend:
    image:  registry.cn-beijing.aliyuncs.com/vitalitytex/scm-frontend:base
    ports:
    - "80:8080"
    environment:
    - NODE_ENV = "production"
    command: tail -f /dev/null
    volumes:
      - ../:/usr/src/app
